---
# Ansible playbook for deploying Tendermint to a group of target nodes
- hosts: tendermint
  become: yes
  become_user: root
  vars:
    # For this script to work, you need a `node_groups` variable whose entries
    # correspond to the configurations for each and every node group you want to
    # deploy.
    copy_node_config: yes
  roles:
    - tendermint
