---
- hosts: tendermint
  become: yes
  become_user: root
  vars:
    local_log_path: /tmp/tendermint-logs/
  tasks:
    - name: Ensure Tendermint service is stopped
      service: name=tendermint state=stopped
    
    - name: Archive log files for node
      archive: 
        path: "/var/log/tendermint*"
        dest: /tmp/tendermint-logs.tar.bz2
    
    - name: Fetch compressed logs
      fetch:
        src: /tmp/tendermint-logs.tar.bz2
        dest: "{{ local_log_path }}/{{ inventory_hostname }}/tendermint-logs.tar.bz2"
        flat: yes
  
    - name: Unarchive compressed logs locally
      become: no
      local_action: "command tar xf {{ local_log_path }}/{{ inventory_hostname }}/tendermint-logs.tar.bz2 -C {{ local_log_path }}/{{ inventory_hostname }}"
