# Ansible playbook for simplifying the process of executing Terraform locally
# and extracting output variables from the execution.
---
- hosts: 127.0.0.1
  connection: local
  become: no
  vars:
    project_path: ""
    input_vars_file: ""
    state: present
    workspace: ""
    output_vars_template: ""
    output_vars_file: ""
  tasks:
    - name: Apply Terraform service configuration
      terraform:
        project_path: "{{ project_path }}"
        variables_file: "{{ input_vars_file }}"
        state: "{{ state }}"
        force_init: yes
        workspace: "{{ workspace }}"
      register: terraform_output

    - debug:
        var: terraform_output
    
    - name: Dump output variables to file
      template:
        src: "{{ output_vars_template }}"
        dest: "{{ output_vars_file }}"
      when: state == "present"
