---
- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
    - name: Apply monitoring service configuration
      terraform:
        project_path: ./monitor
        variables_file: "{{ monitor_vars_file }}"
        state: "{{ state }}"
        force_init: yes
        workspace: "{{ resource_group_id }}"
      when: apply_monitoring == True
      register: monitoring
    
    - debug:
        var: monitoring

    - name: Add deployed monitoring node SSH key to local known_hosts
      shell: |
        ssh-keyscan {{ monitoring.outputs.host.value.public_dns }} >> ~/.ssh/known_hosts
      when: apply_monitoring == True and state == "present"

    # - name: Create Tendermint network Terraform variables for deployed monitoring
    #   template:
    #     src: "{{ tendermint_vars_template }}"
    #     dest: "{{ tendermint_vars_file }}"
    #   when: apply_monitoring

    # - name: Apply Tendermint AWS configuration
    #   terraform:
    #     project_path: ./tendermint
    #     variables_file: "{{ tendermint_vars_file }}"
    #     state: "{{ state }}"
    #     state_file: "{{ tendermint_state_file }}"
    #   register: tendermint

    # - name: Add all deployed Tendermint nodes'
    
    # - name: Apply Tendermint configuration
    #   shell: ansible-playbook
    #   when: state == "present"
